### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by nenonano** [caiosweet/Home-Assistant-custom-components-DPC-Alert#2]
HA 0.99.2, DPC rel 1feb76b

my conf:
- platform: dpc
  istat: 026064
  warnings:
    - temporali_oggi
    - idraulico_oggi
    - idrogeologico_oggi
    - temporali_domani
    - idraulico_domani
    - idrogeologico_domani

I keep having this error in the logs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 266, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 300, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 153, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/dpc/binary_sensor.py", line 109, in is_on
    data = self._updater.dpc_output[self._warning_key]
TypeError: 'NoneType' object is not subscriptable

**Comment by caiosweet** [comment]
try to put the Istat code in quotes.  or remove zero at the beginning.
