### ISSUE TITLE
Feedparser 5.2.1 not supported in python 3.8 (virtualenv)

### ISSUE THREAD

**Issue by millallo** [caiosweet/Home-Assistant-custom-components-DPC-Alert#20]
**Describe the bug**
I just upgraded the python virtualenv of my HA installation (108.2) from 3.7 to 3.8.6, but during boot I get this error:
```
2020-11-22 19:27:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/config_entries.py", line 827, in async_forward_entry_setup
    result = await async_setup_component(self.hass, domain, self._hass_config)
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/setup.py", line 57, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/config_entries.py", line 827, in async_forward_entry_setup
    result = await async_setup_component(self.hass, domain, self._hass_config)
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/setup.py", line 57, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/config_entries.py", line 827, in async_forward_entry_setup
    result = await async_setup_component(self.hass, domain, self._hass_config)
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/setup.py", line 57, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/helpers/discovery.py", line 186, in async_load_platform
    setup_success = await setup.async_setup_component(hass, component, hass_config)
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/setup.py", line 57, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/setup.py", line 64, in async_setup_component
    return await task  # type: ignore
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/setup.py", line 174, in _async_setup_component
    processed_config = await conf_util.async_process_component_config(
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/config.py", line 823, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/loader.py", line 424, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/opt/ha/venv/lib/python3.8/site-packages/homeassistant/loader.py", line 429, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/ha/config/custom_components/dpc/binary_sensor.py", line 8, in <module>
    import feedparser
  File "/opt/ha/venv/lib/python3.8/site-packages/feedparser.py", line 316
    raise KeyError, "object doesn't have key 'category'"
                  ^
SyntaxError: invalid syntax
```

Now all DPC and not-DPC binary_sensors are gone away!
Everything worked fine with python-3.7

**Comment by caiosweet** [comment]
In the manifest.json 
try updating the version from 6.0.0 onwards

` "requirements": ["feedparser==6.0.2"] `

...or in your Python environment pip install --upgrade feedparser

Let me know if it works.

**Comment by millallo** [comment]
yes!
I changed the requirements and upgraded feedparser to 6.0.2, no more Exceptions, all binary sensors are back.

thanks caiosweet!

**Comment by caiosweet** [comment]
fix published
